<?php $helper = Mage::helper('newsletterpopup');?>
<select
    name="<?php echo $this->getName();?>"
    class="esns-additional-field esns-additional-field-<?php echo $this->getName();?>"
    id="esns_additional_<?php echo $this->getName();?>"
>
    <option value=""><?php echo $helper->translate('choose').' '.$this->getLabel(); ?></option>
    <?php if ($options = $helper->getSelectFieldOptions($this->getData())) : ?>
        <?php foreach ($options as $option): ?>
            <option value="<?php echo $option;?>"><?php echo $option;?></option>
        <?php endforeach;?>
    <?php endif; ?>
</select>

